
syntax on
set number
set expandtab
set tabstop=2
set sw=2
set backspace=indent,eol,start
set laststatus=2
set showmatch
set history=100

colo sublimemonokai

inoremap jk <ESC>

nnoremap , :bn<CR>
nnoremap gc 0i#<ESC>
vnoremap gc 0<C-v>I#<ESC>
nmap gc gg0VG''

nnoremap zz :w<CR>

nnoremap - :w<CR>:E<CR> :set number<CR>
nnoremap <CR> A<CR><ESC>
inoremap ;; <C-n>

