eval "$(/opt/homebrew/bin/brew shellenv)"

set -o vi

export PATH='/usr/local/bin:/usr/bin:/usr/sbin:/bin:/Library/Apple/usr/bin:/opt/homebrew/bin:/Users/walkerobrien/Desktop/projects/misc/fabric-samples/bin:/sbin'
export EDITOR=nvim
export NODE_OPTIONS=--no-experimental-fetch

source ~/.zshrc


