eval "$(/opt/homebrew/bin/brew shellenv)"

set -o vi

export PATH='/opt/homebrew/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/Library/Apple/usr/bin:/opt/homebrew/bin:/Users/walkerobrien/Desktop/projects/misc/fabric-samples/bin:/sbin:/usr/local/bin/bin'

. "$HOME/.cargo/env"

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

export EDITOR="nvim"
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
fi

source ~/.zshrc > /dev/null 2>&1
source ~/.zshrc.secret > /dev/null 2>&1

source .env > /dev/null 2>&1



# Added by Toolbox App
export PATH="$PATH:/usr/local/bin"

