export EDITOR=nvim

alias h='hstr'

alias merge-r='git checkout stage; git pull; git merge main; git push; git checkout test; git pull; git merge stage; git push; git checkout dev; git pull; git merge test; git push; git checkout ops; git pull; git merge dev; git push ; git checkout ops'
alias merge-a='merge-d; merge-t; merge-s; merge-m'

alias merge-o='git checkout ops; git pull; git merge walker; git push; git checkout walker'
alias merge-d='git checkout dev; git pull; git merge ops; git push; git checkout ops'
alias merge-t='git checkout test; git pull; git merge dev; git push; git checkout ops'
alias merge-s='git checkout stage; git pull; git merge test; git push; git checkout ops'
alias merge-m='git checkout main; git pull; git merge stage; git push; git checkout ops'

alias merge-z='git checkout main; git pull; git merge dev; git push; git checkout dev'

alias merge-tf='git checkout tf-docs; git pull; git merge main; git push; git checkout main'
alias merge-ft='git checkout main; git pull; git merge tf-docs; git push'

# Ssh file manipulations
alias mw='gcloud config set account walker.obrien@mavenwave.com; cp ~/.ssh/id_rsa.mw ~/.ssh/id_rsa; cp ~/.ssh/id_rsa.pub.mw ~/.ssh/id_rsa.pub'
alias wob='gcloud config set account wnobrien@lakegames.us; cp ~/.ssh/id_rsa.wob ~/.ssh/id_rsa; cp ~/.ssh/id_rsa.pub.wob ~/.ssh/id_rsa.pub'

alias getpub='cat ~/.ssh/id_rsa.pub'

# for x in `docker images | awk '{print $3}'`; do docker image rm $x --force ; done
alias ss='source ./bin/env.sh'
alias ops='source ./bin/env.sh ops'
alias dev='source ./bin/env.sh dev'
alias testt='source ./bin/env.sh test'
alias stage='source ./bin/env.sh stage'
alias prod='source ./bin/env.sh prod'


alias cdt='cd ~/Desktop/projects/terraform-modules'
alias cdh='cd ~/Desktop/projects/helm-charts'
alias cde='cd ~/Desktop/projects/machine-setup'
alias cda='cd ~/Desktop/projects/apps'

alias cdg='cd ~/Desktop/projects/platforms/shared-gke-platform'

alias cdl='cd ~/Desktop/projects/apps/tbl/lakegames'
alias cdb='cd ~/Desktop/projects/apps/tbl/boatload'

alias cdc='cd ~/Desktop/projects/apps/silas/coleman'
alias cdst='cd ~/Desktop/projects/apps/silas/standwithpaul'
alias cdsl='cd ~/Desktop/projects/apps/silas/slipperyjo'

alias cdd='cd ~/Desktop/projects/apps/obrien/dadcoin'
alias cdp='cd ~/Desktop/projects/apps/obrien/paytonpower'
alias cdf='cd ~/Desktop/projects/apps/obrien/finley'


alias ls='ls -aG'
alias ll='ls -l'

alias l='clear'

alias b='byobu'

alias v='vim .'
alias nv='nvim .'

alias pip='pip3'
alias rss='python manage.py runserver'

alias ys='yarn start'
alias yi='yarn ios'

alias env='source env/bin/activate'
alias deac='deactivate'
alias cmod='chmod +x ./bin/*'

alias sv='source ~/.vimrc'
alias sb='source ~/.zshrc'
alias sp='source ~/.profile'


alias vimv='nvim ~/.vimrc; source ~/.vimrc'
alias vimb='nvim ~/.zshrc; source ~/.zshrc'
alias vimp='nvim ~/.profile; source ~/.profile'
alias vimz="nvim ~/.config/starship.toml"
alias vimc='nvim ~/.config/nvim'


alias tf='terraform'
alias tff='terraform fmt'
alias tfi='terraform init'
alias tfv='terraform validate'
alias tfp='terraform plan'
alias tfa='terraform apply'
alias tfaa='terraform apply -auto-approve'
alias tfd='terraform destroy'



# Kubectl Configurations
# source <(kubectl completion bash)
# source <(kubectl completion zsh)
#
# complete -F __start_kubectl k

alias k='kubectl'
alias kcsc='kubectl config set-context --current --namespace'

alias kgaa='kgp -A | grep nginx-dep; kgp -A | grep api-dep'

alias kg='kubectl get'
alias kd='kubectl describe'
alias kl='kubectl logs'
alias ka='kubectl apply -f'
alias ke='kubectl exec -it'

alias kdn='kd nodes'
alias kdp='kd pods'
alias kds='kd svc'
alias kdi='kd ingress'
alias kdm='kd managedcertificate'
alias kdc='kd ciliumnetworkpolicy'
alias kde='kd externalsecrets'
alias kdip='kd computeaddress'
alias kdz='kd dnsmanagedzone'
alias kdr='kd dnsrecordset'

alias kga='kg all,ingress,managedcertificate,cloudbuildtrigger,computeaddress,dnsrecordset,storagebucket,artifactregistryrepository'
alias kgp='kg pods'
alias kgs='kg svc'
alias kgn='kg nodes'
alias kgi='kg ingress'
alias kgm='kg managedcertificate'
alias kgc='kg ciliumnetworkpolicy'
alias kge='kg externalsecrets'
alias kgip='kg computeaddress'
alias kgz='kg dnsmanagedzone'
alias kgr='kg dnsrecordset'

# Git shortcuts
alias gs='git status'
alias gd='git diff'
alias gss='git status -s'
alias gaa='git add -A'
alias gc='git commit -m'
alias gpp='git fetch; git pull; git push'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/walkerobrien/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/walkerobrien/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '$HOME/google-cloud-sdk/completion.zsh.inc' ]; then . '$HOME/google-cloud-sdk/completion.zsh.inc'; fi

eval "$(starship init zsh)"

export PATH="/usr/local/opt/go@1.16/bin:$PATH"
export PATH=$PATH:$(go env GOPATH)/bin

source ~/.iterm2_shell_integration.zsh


### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/walkerobrien/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
